"""bip.models.mundial — WC2026 model wrapping the shipped lock.

Sprint 0 Ola C. The lock at
src/bip/evaluation/tournaments/locked_predictions/world_cup_2026/lock.json
was generated by the bayesian_bivariate_xg_blended predictor in commit
1589177. MundialModel
does NOT retrain — it exposes those frozen predictions through the
BaseModel contract so the v4 registry can route WC2026 fixtures.
"""

from bip.models.mundial.matchday_validator import MatchdayValidator
from bip.models.mundial.model import (
    DEFAULT_LOCK_PATH,
    MundialModel,
    P_MAX_THRESHOLD,
)

__all__ = [
    "DEFAULT_LOCK_PATH",
    "MatchdayValidator",
    "MundialModel",
    "P_MAX_THRESHOLD",
]
